### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [mbolis/mbolis-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

One last thing - **zsh-theme** is kind of generic - please consider renaming the repository to something else - perhaps mbolis-theme?

**Comment by mbolis** [comment]
@unixorn I added both license file and screenshot.
Also changed the name, but please note the name of the theme is supposed to be (somewhat narcissistically) named just "mbolis".
Thank you for your interest!

**Comment by unixorn** [comment]
Sure. I always strip off trailing zsh-theme or -theme from the link names anyway 😄
